In [1]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import chi2_contingency
from scipy import stats

In [2]:
x=pd.read_csv('../../_xlable4_withNa_AllColumns.txt')
y=pd.read_csv('../../_targelable4_withNa_AllColumns.txt')

y=y[['Unnamed: 0','L100100', ]]

In [3]:
data= pd.merge(x,y, how='inner',left_on='Unnamed: 0', right_on='Unnamed: 0')
data['max']=np.min(data[['FIELD_6','FIELD_7']],axis=1)
data=data.drop(columns=['FIELD_6','FIELD_7'])

In [5]:
# filter the data set 
data=data[data.FIELD_16!=1] # exclude people who are diagnosed for (diabetes) 
data=data[data.FIELD_23!=1] # exclude people who are on medication for diabetes

data=data[data.FIELD_15!=1] # exclude people who are diagnosed for (high blood pressure)
data=data[data.FIELD_22!=1] # exclude people who are on medication for high blood pressure

data=data[data.FIELD_17!=1] # exclude people who are diagnosed for hyperlipidemia
data=data[data.FIELD_24!=1] # exclude people who are on medication for hyperlipidemia

print(data.shape)

(159381, 408)

In [6]:
#split column types to categorical and numerical
numerical_cols = list(data.columns[~data.columns.str.startswith('FIELD')])
categorical_cols = list(data.columns[data.columns.str.startswith('FIELD')])

Calculate correlation Value - for numerical values
========

In [7]:
corr=data[numerical_cols].corr()
corr=corr.L100100_y
corrvalPD=pd.DataFrame()
corrvalPD['Col']=corr.index
corrvalPD['val']=abs(corr.values)

corrvalPD=corrvalPD.sort_values(by='val',ascending=False)
corrvalPD.head()

           Col  val
134    L393800  1.0
262    S004418  1.0
278  L100100_y  1.0
261    S004417  1.0
260    S004416  1.0

In [8]:
#count of none NA values of feature set
mydataset=data.copy()[numerical_cols]
colCount=[]
for i in mydataset.columns:
    colCount.append([i,mydataset[i].dropna().shape[0]])

colCountPD=pd.DataFrame(colCount,columns=['Col','Count'])
colCountPD.head()

          Col   Count
0  Unnamed: 0  159381
1       index  159381
2     COMPARE  159381
3         AGE  159381
4       B_DAY  159381

In [9]:
mergedColCorrCount=pd.merge(corrvalPD,colCountPD,how='inner',left_on='Col',right_on='Col')
mergedColCorrCount=mergedColCorrCount[mergedColCorrCount.Count>50000]
mergedColCorrCount=mergedColCorrCount.sort_values(by='val', ascending=False)
mergedColCorrCount.head(20)

          Col       val   Count
2   L100100_y  1.000000  151195
22  L100100_x  0.281357  148548
28    L100300  0.221676  145101
30       Year  0.211155  159381
32    L500700  0.176816  123706
33    L100200  0.167259  148627
36    L103800  0.157522   66480
53    L104400  0.103656   78410
56    L104500  0.100426   78410
57    COMPARE  0.100115  159381
58    L103300  0.098616  135222
60    L102900  0.096131  158941
61    L101600  0.095709  152251
62    L107500  0.095628  142725
65    L191200  0.089783  143448
67    L103000  0.087217  158939
68    S000501  0.084825  159305
71      B_DAY  0.078270  159381
72    L103200  0.076780  158879
73    L190600  0.076537  145182

In [10]:
print(list(mergedColCorrCount.head(15).Col))

['L100100_y', 'L100100_x', 'L100300', 'Year', 'L500700', 'L100200', 'L103800', 'L104400', 'L104500', 'COMPARE', 'L103300', 'L102900', 'L101600', 'L107500', 'L191200']

Anova test - For categorical values [Questionnaire answers]
=======

In [11]:
mydataset=data.copy()[categorical_cols] #[np.insert(categorical_cols,0,'L100800')]

# mydataset=mydataset.drop(columns=['FIELD_1','FIELD_2','FIELD_8','FIELD_10','FIELD_11','FIELD_12','FIELD_39','FIELD_88',
#                            'FIELD_89','FIELD_109','FIELD_110','FIELD_111','FIELD_70','FIELD_82','FIELD_85','FIELD_91',
#                            'FIELD_103','FIELD_106'])

# mydataset=mydataset.drop(columns=['FIELD_1','FIELD_2','FIELD_87','FIELD_8','FIELD_10','FIELD_11','FIELD_12','FIELD_39',
#                                   'FIELD_88','FIELD_89', 'FIELD_108','FIELD_109','FIELD_110','FIELD_111','FIELD_82',
#                                  'FIELD_91','FIELD_103','FIELD_118','FIELD_119','FIELD_120','FIELD_121','FIELD_122',
#                                  'FIELD_123','FIELD_124','FIELD_125','FIELD_126','FIELD_127','FIELD_128','FIELD_129',
#                                  'FIELD_130','FIELD_131','FIELD_132','FIELD_133','FIELD_134','FIELD_135','FIELD_136',
#                                   'FIELD_137','FIELD_138','FIELD_139','FIELD_140'])


mydataset=mydataset.drop(columns=['FIELD_1','FIELD_2','FIELD_87','FIELD_8','FIELD_10','FIELD_11','FIELD_12','FIELD_39',
                                  'FIELD_88','FIELD_89', 'FIELD_108','FIELD_109','FIELD_110','FIELD_111','FIELD_82',
                                 'FIELD_91','FIELD_103','FIELD_118','FIELD_119','FIELD_120','FIELD_121','FIELD_122',
                                 'FIELD_123','FIELD_124','FIELD_125','FIELD_126','FIELD_127','FIELD_128','FIELD_129',
                                 'FIELD_130','FIELD_131','FIELD_132','FIELD_133','FIELD_134','FIELD_135','FIELD_136',
                                  'FIELD_137','FIELD_138','FIELD_139','FIELD_140',
                                  'FIELD_64','FIELD_65','FIELD_66','FIELD_67','FIELD_68','FIELD_69','FIELD_70','FIELD_72',
                                  'FIELD_73','FIELD_74','FIELD_75','FIELD_76','FIELD_77','FIELD_80','FIELD_81','FIELD_84',
                                  'FIELD_85','FIELD_90','FIELD_93','FIELD_94','FIELD_95','FIELD_96','FIELD_97','FIELD_98',
                                  'FIELD_101','FIELD_102','FIELD_105','FIELD_106','FIELD_112','FIELD_113','FIELD_114',
                                  'FIELD_115','FIELD_116','FIELD_117','FIELD_118','FIELD_119','FIELD_9'
                                 ])


mydataset=mydataset.drop(mydataset[mydataset.FIELD_3=='`'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_3=='G'].index)


mydataset=mydataset.drop(mydataset[mydataset.FIELD_4=='.'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_5=='.'].index)

mydataset=mydataset.drop(mydataset[mydataset.FIELD_35=='?'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_35=='.'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_36=='.'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_37=='\\'].index)
 
# mydataset=mydataset.drop(mydataset[mydataset.FIELD_39 == '7+' ].index)
# mydataset=mydataset.drop(mydataset[mydataset.FIELD_39 == '5~7'].index)
# mydataset=mydataset.drop(mydataset[mydataset.FIELD_39 == '3-4'].index)


# mydataset=mydataset.drop(mydataset[mydataset.FIELD_95=='.'].index)

In [12]:
colslist=mydataset.columns
DiabeticColVals=data.L100100_y

cor=[]
pval=[]
count=[]

for i in range(len(colslist)):
    print(i,colslist[i])
    
    temp=pd.DataFrame([])
    temp['a']=DiabeticColVals
    temp['b']=mydataset[colslist[i]].astype(float)
    temp=temp.dropna()
    count.append(temp.shape[0])
    
    uniquevalues=temp.b.unique()
    
    selectedGroupVals=[]
    for k in range(len(uniquevalues)):
        selectedGroupVals.append(np.asarray(temp[temp['b']==uniquevalues[k]].a))

    F, p = stats.f_oneway(*selectedGroupVals)
    cor.append(F)
    pval.append(p)

0 FIELD_3
1 FIELD_4
2 FIELD_5
3 FIELD_13
4 FIELD_14
5 FIELD_15
6 FIELD_16
7 FIELD_17
8 FIELD_18
9 FIELD_19
10 FIELD_20
11 FIELD_21
12 FIELD_22
13 FIELD_23
14 FIELD_24
15 FIELD_25
16 FIELD_26
17 FIELD_27
18 FIELD_28
19 FIELD_29
20 FIELD_30
21 FIELD_31
22 FIELD_32
23 FIELD_33
24 FIELD_34
25 FIELD_35
26 FIELD_36
27 FIELD_37
28 FIELD_38
29 FIELD_40
30 FIELD_41
31 FIELD_42
32 FIELD_43
33 FIELD_44
34 FIELD_45
35 FIELD_46
36 FIELD_47
37 FIELD_48
38 FIELD_49
39 FIELD_50
40 FIELD_51
41 FIELD_52
42 FIELD_53
43 FIELD_54
44 FIELD_55
45 FIELD_56
46 FIELD_57
47 FIELD_58
48 FIELD_59
49 FIELD_60
50 FIELD_61
51 FIELD_62
52 FIELD_63

In [13]:
FvalPvalCorr=pd.DataFrame()    
FvalPvalCorr['Cols']=colslist
FvalPvalCorr['F']=cor
FvalPvalCorr['P']=pval
FvalPvalCorr['Count']=count
FvalPvalCorr=FvalPvalCorr.sort_values(by='F', ascending=False)

In [14]:
FvalPvalCorr[FvalPvalCorr.Count>50000].head(10)

        Cols           F              P   Count
23  FIELD_33  179.822719  1.557704e-191  150896
30  FIELD_41   14.771441   2.173573e-19  150883
29  FIELD_40   14.012642   2.714743e-18  150913
1    FIELD_4   13.275211   3.137587e-17  148877
15  FIELD_25   10.856978   9.844678e-04  151178
22  FIELD_32   10.383640   4.259739e-13  150708
8   FIELD_18   10.292568   1.335949e-03  151177
31  FIELD_42    9.646138   1.827532e-13  150866
19  FIELD_29    9.568966   1.979302e-03  151177
11  FIELD_21    7.356048   6.684511e-03  151178

In [15]:
print(list(FvalPvalCorr[FvalPvalCorr.Count>50000].Cols)[:10])

['FIELD_33', 'FIELD_41', 'FIELD_40', 'FIELD_4', 'FIELD_25', 'FIELD_32', 'FIELD_18', 'FIELD_42', 'FIELD_29', 'FIELD_21']

========================= LASSO method
================

In [16]:
selectedcols=['L100100_y', 'L100100_x', 'L100300', 'Year', 'L500700', 'L100200', 'L103800', 'L104400', 
              'L104500', 'COMPARE', 'L103300', 'L102900', 'L101600', 'L107500', 'L191200','FIELD_33', 
              'FIELD_41', 'FIELD_40', 'FIELD_4', 'FIELD_25', 'FIELD_32', 'FIELD_18', 'FIELD_42', 'FIELD_29', 'FIELD_21'
             ]
data2=data[selectedcols].copy().dropna()
print(data2.shape)

(44683, 25)

In [18]:
x=data2[['L100100_x', 'L100300', 'Year', 'L500700', 'L100200', 'L103800', 'L104400', 
              'L104500', 'COMPARE', 'L103300', 'L102900', 'L101600', 'L107500', 'L191200','FIELD_33', 
              'FIELD_41', 'FIELD_40', 'FIELD_4', 'FIELD_25', 'FIELD_32', 'FIELD_18', 'FIELD_42', 'FIELD_29', 'FIELD_21']]
y=data2.L100100_y

In [19]:
from sklearn import linear_model
clf = linear_model.Lasso(alpha=0.1)
clf.fit(x,y)

print(clf.coef_)

print(clf.intercept_)  

# pd.DataFrame([x.columns.ravel(),clf.coef_.ravel()],columns=['Name','coeff'])

lassod=pd.DataFrame()
lassod['Name']=x.columns
lassod['coeff']=clf.coef_
lassod

lassod=lassod.drop(lassod[lassod.coeff==0].index)
lassod.coeff=abs(lassod.coeff)
lassod=lassod.sort_values(by='coeff', ascending=False)
lassod

[ 0.00000000e+00  0.00000000e+00  1.14590880e-02 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  5.55320211e-04  4.57992484e-04
  3.04230071e-16  0.00000000e+00  9.88970689e-04  2.39810680e-03
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00]
-16.66202322804099

       Name         coeff
2      Year  1.145909e-02
11  L101600  2.398107e-03
10  L102900  9.889707e-04
6   L104400  5.553202e-04
7   L104500  4.579925e-04
8   COMPARE  3.042301e-16

In [20]:
print(list(lassod.Name[:16]))

['Year', 'L101600', 'L102900', 'L104400', 'L104500', 'COMPARE']

=============================== SelectKBest method
========================

In [21]:
# from sklearn.feature_selection import chi2
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import SelectKBest

bestfeatures = SelectKBest(score_func=f_regression, k=10)
fit = bestfeatures.fit(x,y)

dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

featureScores = pd.concat([dfcolumns,dfscores],axis=1)
featureScores.columns = ['Specs','Score']  #naming the dataframe columns

# x=x[x.columns[:15]]
print(list(x.columns[:16]))

['L100100_x', 'L100300', 'Year', 'L500700', 'L100200', 'L103800', 'L104400', 'L104500', 'COMPARE', 'L103300', 'L102900', 'L101600', 'L107500', 'L191200', 'FIELD_33', 'FIELD_41']

========================================= LinearSVC
===============

In [22]:
# from sklearn.svm import LinearSVC
# from sklearn.datasets import load_iris
# from sklearn.feature_selection import SelectFromModel

# lsvc = LinearSVC(C=0.01, penalty="l1", dual=False).fit(x, y)
# model = SelectFromModel(lsvc, prefit=True)
# X_new = model.transform(x)
# X_new.shape

In [23]:
# X_new

================================ SequentialFeatureSelector 
================================

In [24]:
# from sklearn.linear_model import LinearRegression
# from mlxtend.feature_selection import SequentialFeatureSelector as SFS
# from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
# from sklearn.ensemble import RandomForestRegressor

# lr = RandomForestRegressor()

# sfs = SFS(lr, 
#           k_features=13, 
#           forward=True, 
#           floating=False, 
#           scoring='neg_mean_squared_error',
#           cv=5)

# sfs = sfs.fit(x, y)
# fig = plot_sfs(sfs.get_metric_dict(), kind='std_err')

# plt.title('Sequential Forward Selection (w. StdErr)')
# plt.grid()
# plt.show()

================================= feature_importances
=====

In [25]:
from sklearn.ensemble import ExtraTreesRegressor
import matplotlib.pyplot as plt
model = ExtraTreesRegressor()
model.fit(x,y)

print(model.feature_importances_) #use inbuilt class feature_importances of tree based classifiers

#plot graph of feature importances for better visualization
feat_importances = pd.Series(model.feature_importances_, index=x.columns)
feat_importances.nlargest(16).plot(kind='barh')
plt.show()

print(feat_importances.nlargest(16))
print(feat_importances.nlargest(16).index)

ValueError: Unknown label type: 'continuous'

============================= Backward Elimination
========

In [26]:
import statsmodels.regression.linear_model as sm
temp=x.copy()
temp['const']=np.ones((x.shape[0],1))
regressor_OLS = sm.OLS(endog = y, exog = temp).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              L100100_y   R-squared:                       0.127
Model:                            OLS   Adj. R-squared:                  0.126
Method:                 Least Squares   F-statistic:                     808.9
Date:                Wed, 23 Oct 2019   Prob (F-statistic):               0.00
Time:                        01:55:53   Log-Likelihood:                -27560.
No. Observations:               44683   AIC:                         5.514e+04
Df Residuals:                   44674   BIC:                         5.522e+04
Df Model:                           8
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
L100100_x      0.1783      0.004     41.398      0.000       0.170       0.187
L100300        0.1024      0.003     37.533      0.000       0.097       0.108
Year           0.0025   2.87e-05     88.674      0.000       0.002       0.003
L500700       -0.0279      0.003     -9.512      0.000      -0.034      -0.022
L100200        0.0765      0.003     29.919      0.000       0.072       0.082
L103800        0.0543      0.006      8.803      0.000       0.042       0.066
L104400        0.0004   6.21e-05      6.160      0.000       0.000       0.001
L104500        0.0003   4.19e-05      6.316      0.000       0.000       0.000
COMPARE     3.467e-16   1.65e-17     20.964      0.000    3.14e-16    3.79e-16
L103300        0.0481      0.002     19.569      0.000       0.043       0.053
L102900       -0.0005   7.92e-05     -6.919      0.000      -0.001      -0.000
L101600        0.0018      0.000     11.708      0.000       0.001       0.002
L107500       -0.0180      0.005     -3.886      0.000      -0.027      -0.009
L191200       -0.0709      0.003    -26.337      0.000      -0.076      -0.066
FIELD_33      -0.0524      0.003    -18.263      0.000      -0.058      -0.047
FIELD_41      -0.0051      0.002     -2.884      0.004      -0.009      -0.002
FIELD_40       0.0001      0.002      0.055      0.956      -0.003       0.004
FIELD_4       -0.0050      0.002     -2.886      0.004      -0.008      -0.002
FIELD_25      -0.0755      0.005    -13.973      0.000      -0.086      -0.065
FIELD_32      -0.0084      0.004     -2.319      0.020      -0.016      -0.001
FIELD_18      -0.0951      0.007    -13.993      0.000      -0.108      -0.082
FIELD_42       0.0044      0.001      4.320      0.000       0.002       0.006
FIELD_29      -0.0023      0.006     -0.386      0.699      -0.014       0.010
FIELD_21      -0.0004   2.61e-05    -16.776      0.000      -0.000      -0.000
const       5.438e-05    2.1e-06     25.882      0.000    5.03e-05    5.85e-05
==============================================================================
Omnibus:                     1986.518   Durbin-Watson:                   1.980
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2551.511
Skew:                           0.464   Prob(JB):                         0.00
Kurtosis:                       3.713   Cond. No.                     4.21e+17
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.21e+17. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
temp=temp.drop(columns=['L103000','L103300','L190300','FIELD_40','FIELD_27','FIELD_29','FIELD_21','FIELD_5','FIELD_14'])
regressor_OLS = sm.OLS(endog = y, exog = temp).fit()
regressor_OLS.summary()

In [ ]:
temp=temp.drop(columns=['FIELD_33'])
regressor_OLS = sm.OLS(endog = y, exog = temp).fit()
regressor_OLS.summary()

In [ ]:
temp.columns