In [1]:
import numpy as np
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import chi2_contingency
from scipy import stats

In [2]:
data= pd.read_csv('../sep19SexAndAgeAddedFINAL DATASET_ver2.txt',sep=',')
data=data.drop(columns=['B_DAY'])

In [3]:
# data=data.query('FIELD_15 !=1 and FIELD_17 !=1 and FIELD_22 != 1 and FIELD_24 != 1 and FIELD_16 != 1 and FIELD_23 != 1 and FIELD_30 != 1')
data=data.query('FIELD_16 != 1 and FIELD_23 != 1')

In [4]:
# data=data[data.SEX==0]
# data=data[data.FIELD_15!=1]
# data=data[data.FIELD_17!=1]
# data=data[data.FIELD_22!=1]
# data=data[data.FIELD_24!=1]
# data=data[data.AGE>=40]
# data=data[data.AGE<50]

In [5]:
df=data.copy()
conditions3 = [
    (df.L100800 < 100)  ,
    (df.L100800 >= 100) & (df.L100800 < 126),
    (df.L100800 >= 126)]
choices3 = [0,1,2]
df['CLASS'] = np.select(conditions3, choices3, default=0)
df.head()
data=df.copy()

In [6]:
#split column types to categorical and numerical
numerical_cols = list(data.columns[~data.columns.str.startswith('FIELD')])
categorical_cols = list(data.columns[data.columns.str.startswith('FIELD')])
categorical_cols.append('CLASS')

Calculate correlation Value - for numerical values
========

In [7]:
corr=data[numerical_cols].corr()

In [8]:
val= pd.DataFrame(corr['L103000']).sort_values(by='L103000', ascending=False)
# val.head(15)

mydataset=data.copy()[numerical_cols]
colslist_original=mydataset.columns
DiabeticColVals_original=mydataset.L103000

cor_original=[]
count_original=[]

for i in range(len(colslist_original)):
    print(i,colslist_original[i])
    
    temp=pd.DataFrame([])
    temp['a']=DiabeticColVals_original
    temp['b']=mydataset[colslist_original[i]]
    temp=temp.dropna()
    count_original.append(temp.shape[0])
    tempcor=temp.corr()
    
    if(tempcor.shape[0]>1):
        print(temp.shape)
        cor_original.append(abs(tempcor.b[0]))
    else:
        cor_original.append(0)

0 Unnamed: 0
(514929, 2)
1 COMPARE
(514929, 2)
2 AGE
(514926, 2)
3 SEX
(514926, 2)
4 L100100
(494661, 2)
5 L100200
(495079, 2)
6 L100300
(486817, 2)
7 L100400
(493928, 2)
8 L100500
(514860, 2)
9 L100700
(495675, 2)
10 L100800
(514917, 2)
11 L101000
(500975, 2)
12 L101100
(268155, 2)
13 L101200
(514918, 2)
14 L101300
(514918, 2)
15 L101400
(444335, 2)
16 L101600
(500862, 2)
17 L101700
(514882, 2)
18 L102000
(77186, 2)
19 L102200
(5980, 2)
20 L102400
(335480, 2)
21 L102500
(17500, 2)
22 L102700
(273863, 2)
23 L102800
(942, 2)
24 L102900
(514926, 2)
25 L103000
(514929, 2)
26 L103100
(514187, 2)
27 L103200
(514172, 2)
28 L103300
(440211, 2)
29 L103400
(192614, 2)
30 L103500
(192554, 2)
31 L103600
(186623, 2)
32 L103700
(220922, 2)
33 L103800
(223315, 2)
34 L103900
(8346, 2)
35 L104000
(10163, 2)
36 L104200
(9026, 2)
37 L104300
(285331, 2)
38 L104400
(269204, 2)
39 L104500
(269207, 2)
40 L104600
(181011, 2)
41 L104800
(14, 2)
42 L104900
(16963, 2)
43 L105200
(514759, 2)
44 L105300
(17, 2)
45 L105700
(20, 2)
46 L107400
(487211, 2)
47 L107500
(481426, 2)
48 L107600
(9291, 2)
49 L107700
(188766, 2)
50 L108000
(1, 2)
51 L108600
(60792, 2)
52 L108700
(60795, 2)
53 L112000
(106, 2)
54 L114200
(13471, 2)
55 L114300
(13910, 2)
56 L114500
(513, 2)
57 L115400
(2939, 2)
58 L115500
(2496, 2)
59 L117700
(2, 2)
60 L120100
(8, 2)
61 L120200
(1, 2)
62 L120300
(16106, 2)
63 L120600
(2, 2)
64 L120700
(16994, 2)
65 L120800
(1, 2)
66 L120900
(1, 2)
67 L121300
(16385, 2)
68 L121400
(1, 2)
69 L122000
(7, 2)
70 L132900
(5, 2)
71 L138200
(181, 2)
72 L142800
(10985, 2)
73 L156100
(60835, 2)
74 L157100
(1, 2)
75 L157400
(1360, 2)
76 L157500
(36, 2)
77 L160100
(1, 2)
78 L160200
(1, 2)
79 L190000
(513923, 2)
80 L190201
(508935, 2)
81 L190202
(508925, 2)
82 L190203
(508925, 2)
83 L190204
(508925, 2)
84 L190205
(508925, 2)
85 L190206
(508925, 2)
86 L190207
(508925, 2)
87 L190208
(508925, 2)
88 L190209
(508925, 2)
89 L190210
(508925, 2)
90 L190211
(508925, 2)
91 L190300
(513960, 2)
92 L190400
(514876, 2)
93 L190500
(513807, 2)
94 L190600
(487729, 2)
95 L190700
(489567, 2)
96 L190800
(489565, 2)
97 L190900
(484259, 2)
98 L191000
(508940, 2)
99 L191100
(441009, 2)
100 L191200
(481326, 2)
101 L191300
(486295, 2)
102 L191500
(7692, 2)
103 L200500
(34612, 2)
104 L200600
(1, 2)
105 L200700
(8068, 2)
106 L201501
(100, 2)
107 L201502
(100, 2)
108 L201503
(100, 2)
109 L201600
(105, 2)
110 L202700
(32, 2)
111 L210515
(379, 2)
112 L302800
(3560, 2)
113 L303000
(9, 2)
114 L303201
(4, 2)
115 L303202
(4, 2)
116 L303203
(4, 2)
117 L303204
(4, 2)
118 L303205
(4, 2)
119 L305900
(3, 2)
120 L314900
(435, 2)
121 L315100
(1896, 2)
122 L327300
(9742, 2)
123 L336400
(334, 2)
124 L345700
(16227, 2)
125 L345800
(17433, 2)
126 L349100
(7, 2)
127 L359000
(25, 2)
128 L368900
(36, 2)
129 L377800
(309893, 2)
130 L382800
(4, 2)
131 L382900
(6, 2)
132 L393800
(6, 2)
133 L394600
(180, 2)
134 L395000
(184, 2)
135 L397100
(5669, 2)
136 L401202
(504966, 2)
137 L401203
(504966, 2)
138 L403000
(1, 2)
139 L403100
(0, 2)
140 L403300
(15, 2)
141 L500200
(11486, 2)
142 L500300
(84, 2)
143 L500400
(476570, 2)
144 L500500
(6, 2)
145 L500700
(416917, 2)
146 L500800
(217511, 2)
147 L500900
(7, 2)
148 L501600
(3, 2)
149 L501700
(1950, 2)
150 L501800
(16369, 2)
151 L501900
(17, 2)
152 L502000
(4, 2)
153 L502100
(1, 2)
154 L502300
(13953, 2)
155 L502500
(1111, 2)
156 L502600
(4, 2)
157 L502700
(22539, 2)
158 L502800
(3879, 2)
159 L503200
(2, 2)
160 L504700
(445283, 2)
161 L504800
(33328, 2)
162 L504900
(2, 2)
163 L505300
(267151, 2)
164 L505600
(17983, 2)
165 L505700
(369663, 2)
166 L505800
(203500, 2)
167 L505900
(373, 2)
168 L506300
(30635, 2)
169 L510100
(2141, 2)
170 L510400
(1, 2)
171 L510700
(1, 2)
172 L511000
(2409, 2)
173 L511200
(386, 2)
174 L511300
(412, 2)
175 L512300
(360, 2)
176 L512400
(88644, 2)
177 L512900
(1, 2)
178 L518900
(4, 2)
179 L520100
(33, 2)
180 L520300
(1, 2)
181 L533900
(1, 2)
182 L534700
(43991, 2)
183 L540100
(1, 2)
184 L550300
(4, 2)
185 L573601
(897, 2)
186 L573602
(897, 2)
187 L573603
(897, 2)
188 L573604
(897, 2)
189 L573605
(897, 2)
190 L573606
(897, 2)
191 L573607
(897, 2)
192 L573608
(897, 2)
193 L573609
(897, 2)
194 L573610
(897, 2)
195 L573701
(320, 2)
196 L573702
(320, 2)
197 L573703
(320, 2)
198 L573704
(320, 2)
199 L573705
(320, 2)
200 L573706
(320, 2)
201 L573707
(320, 2)
202 L573708
(320, 2)
203 L573709
(320, 2)
204 L573710
(320, 2)
205 L575500
(1, 2)
206 R602300
(2256, 2)
207 R602400
(2, 2)
208 R602800
(556, 2)
209 S000100
(514700, 2)
210 S000200
(514676, 2)
211 S000300
(513763, 2)
212 S000400
(3, 2)
213 S000501
(514761, 2)
214 S000502
(514761, 2)
215 S000503
(15512, 2)
216 S000504
(15514, 2)
217 S000600
(77595, 2)
218 S000701
(316308, 2)
219 S000702
(316268, 2)
220 S000703
(198299, 2)
221 S000704
(198340, 2)
222 S001001
(105407, 2)
223 S001002
(105405, 2)
224 S001003
(110228, 2)
225 S001004
(105410, 2)
226 S001005
(110224, 2)
227 S001006
(110223, 2)
228 S001101
(16005, 2)
229 S001102
(15994, 2)
230 S001200
(513664, 2)
231 S001300
(0, 2)
232 S001400
(1, 2)
233 S001901
(399303, 2)
234 S001902
(399301, 2)
235 S001903
(399864, 2)
236 S001904
(399862, 2)
237 S001905
(399315, 2)
238 S001906
(399313, 2)
239 S001907
(399302, 2)
240 S001908
(399296, 2)
241 S002701
(77913, 2)
242 S002702
(77912, 2)
243 S004401
(36759, 2)
244 S004402
(36760, 2)
245 S004403
(36760, 2)
246 S004404
(36760, 2)
247 S004405
(36761, 2)
248 S004406
(36761, 2)
249 S004407
(36759, 2)
250 S004408
(36758, 2)
251 S004409
(36760, 2)
252 S004410
(36760, 2)
253 S004411
(36730, 2)
254 S004412
(36717, 2)
255 S004413
(30, 2)
256 S004414
(21, 2)
257 S004415
(12, 2)
258 S004416
(12, 2)
259 S004417
(23, 2)
260 S004418
(23, 2)
261 S004419
(27, 2)
262 S004420
(27, 2)
263 S004421
(30, 2)
264 S004422
(30, 2)
265 S004423
(9, 2)
266 S004424
(9, 2)
267 S005200
(2, 2)
268 S007400
(22, 2)
269 S008501
(1580, 2)
270 S008502
(40, 2)
271 S008503
(1565, 2)
272 S008504
(1563, 2)
273 S010101
(444541, 2)
274 S010102
(444550, 2)
275 CLASS
(514929, 2)

In [ ]:
CorValWithCorr=pd.DataFrame()    
CorValWithCorr['Cols']=colslist_original
CorValWithCorr['Corr']=cor_original
CorValWithCorr['Count']=count_original
CorValWithCorr=CorValWithCorr.sort_values(by='Corr', ascending=False)

CorValWithCorr.head(15)

In [ ]:
CorValWithCorr2=CorValWithCorr.copy()
CorValWithCorr2=CorValWithCorr2[CorValWithCorr2.Count>50000].sort_values(by='Corr', ascending=False)
CorValWithCorr2=CorValWithCorr2.reset_index().drop(columns = ['index'])

print(list(CorValWithCorr2.head(22).Cols))
CorValWithCorr2.head(22)

Anova test - For categorical values [Questionnaire answers]
=======

In [17]:
mydataset=data.copy()[categorical_cols] #[np.insert(categorical_cols,0,'L100800')]

# mydataset=mydataset.drop(columns=['FIELD_1','FIELD_2','FIELD_8','FIELD_10','FIELD_11','FIELD_12','FIELD_39','FIELD_88',
#                            'FIELD_89','FIELD_109','FIELD_110','FIELD_111','FIELD_70','FIELD_82','FIELD_85','FIELD_91',
#                            'FIELD_103','FIELD_106'])

mydataset=mydataset.drop(columns=['FIELD_1','FIELD_2','FIELD_87','FIELD_8','FIELD_10','FIELD_11','FIELD_12','FIELD_39',
                                  'FIELD_88','FIELD_89', 'FIELD_108','FIELD_109','FIELD_110','FIELD_111','FIELD_82',
                                 'FIELD_91','FIELD_103','FIELD_118','FIELD_119','FIELD_120','FIELD_121','FIELD_122',
                                 'FIELD_123','FIELD_124','FIELD_125','FIELD_126','FIELD_127','FIELD_128','FIELD_129',
                                 'FIELD_130','FIELD_131','FIELD_132','FIELD_133','FIELD_134','FIELD_135','FIELD_136',
                                  'FIELD_137','FIELD_138','FIELD_139','FIELD_140'])


# mydataset=mydataset.drop(columns=['FIELD_1','FIELD_2','FIELD_8','FIELD_10','FIELD_11','FIELD_12','FIELD_82',
#                                  'FIELD_87','FIELD_88','FIELD_91','FIELD_103','FIELD_108','FIELD_109','FIELD_118',
#                                  'FIELD_119','FIELD_120','FIELD_121','FIELD_122','FIELD_123','FIELD_124','FIELD_125',
#                                   'FIELD_126','FIELD_127','FIELD_128','FIELD_129',
#                                  'FIELD_130','FIELD_131','FIELD_132','FIELD_133','FIELD_134','FIELD_135','FIELD_136',
#                                   'FIELD_137','FIELD_138','FIELD_139','FIELD_140',
#                                  'FIELD_39','FIELD_6','FIELD_9','FIELD_43','FIELD_44','FIELD_45','FIELD_46','FIELD_47',
#                                  'FIELD_59','FIELD_60','FIELD_61'])


mydataset=mydataset.drop(mydataset[mydataset.FIELD_3=='`'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_3=='G'].index)


mydataset=mydataset.drop(mydataset[mydataset.FIELD_4=='.'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_5=='.'].index)

mydataset=mydataset.drop(mydataset[mydataset.FIELD_35=='?'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_35=='.'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_36=='.'].index)
mydataset=mydataset.drop(mydataset[mydataset.FIELD_37=='\\'].index)
 
# mydataset=mydataset.drop(mydataset[mydataset.FIELD_39 == '7+' ].index)
# mydataset=mydataset.drop(mydataset[mydataset.FIELD_39 == '5~7'].index)
# mydataset=mydataset.drop(mydataset[mydataset.FIELD_39 == '3-4'].index)


mydataset=mydataset.drop(mydataset[mydataset.FIELD_95=='.'].index)

In [18]:
colslist=mydataset.columns
DiabeticColVals=data.L103000

cor=[]
pval=[]
count=[]

for i in range(len(colslist)):
    print(i,colslist[i])
    
    temp=pd.DataFrame([])
    temp['a']=DiabeticColVals
    temp['b']=mydataset[colslist[i]].astype(float)
    temp=temp.dropna()
    count.append(temp.shape[0])
    
    uniquevalues=temp.b.unique()
    
    selectedGroupVals=[]
    for k in range(len(uniquevalues)):
        selectedGroupVals.append(np.asarray(temp[temp['b']==uniquevalues[k]].a))

    F, p = stats.f_oneway(*selectedGroupVals)
    cor.append(F)
    pval.append(p)

0 FIELD_3
1 FIELD_4
2 FIELD_5
3 FIELD_6
4 FIELD_7
5 FIELD_9
6 FIELD_13
7 FIELD_14
8 FIELD_15
9 FIELD_16
10 FIELD_17
11 FIELD_18
12 FIELD_19
13 FIELD_20
14 FIELD_21
15 FIELD_22
16 FIELD_23
17 FIELD_24
18 FIELD_25
19 FIELD_26
20 FIELD_27
21 FIELD_28
22 FIELD_29
23 FIELD_30
24 FIELD_31
25 FIELD_32
26 FIELD_33
27 FIELD_34
28 FIELD_35
29 FIELD_36
30 FIELD_37
31 FIELD_38
32 FIELD_40
33 FIELD_41
34 FIELD_42
35 FIELD_43
36 FIELD_44
37 FIELD_45
38 FIELD_46
39 FIELD_47
40 FIELD_48
41 FIELD_49
42 FIELD_50
43 FIELD_51
44 FIELD_52
45 FIELD_53
46 FIELD_54
47 FIELD_55
48 FIELD_56
49 FIELD_57
50 FIELD_58
51 FIELD_59
52 FIELD_60
53 FIELD_61
54 FIELD_62
55 FIELD_63
56 FIELD_64
57 FIELD_65
58 FIELD_66
59 FIELD_67
60 FIELD_68
61 FIELD_69
62 FIELD_70
63 FIELD_72
64 FIELD_73
65 FIELD_74
66 FIELD_75
67 FIELD_76
68 FIELD_77
69 FIELD_80
70 FIELD_81
71 FIELD_84
72 FIELD_85
73 FIELD_90
74 FIELD_93
75 FIELD_94
76 FIELD_95
77 FIELD_96
78 FIELD_97
79 FIELD_98
80 FIELD_101
81 FIELD_102
82 FIELD_105
83 FIELD_106
84 FIELD_112
85 FIELD_113
86 FIELD_114
87 FIELD_115
88 FIELD_116
89 FIELD_117
90 CLASS

In [19]:

FvalPvalCorr=pd.DataFrame()    
FvalPvalCorr['Cols']=colslist
FvalPvalCorr['F']=cor
FvalPvalCorr['P']=pval
FvalPvalCorr['Count']=count
FvalPvalCorr=FvalPvalCorr.sort_values(by='F', ascending=False)

In [20]:
FvalPvalCorr[FvalPvalCorr.Count>50000].head(30)

        Cols             F              P   Count
90     CLASS  29495.464991   0.000000e+00  514913
26  FIELD_33   6269.598433   0.000000e+00  512472
8   FIELD_15   3960.342511   0.000000e+00  513596
10  FIELD_17   2309.035518   0.000000e+00  513201
4    FIELD_7   2077.630820   0.000000e+00  219978
15  FIELD_22   1684.281057   0.000000e+00  508275
31  FIELD_38   1377.729809   0.000000e+00  477525
17  FIELD_24    933.329607  8.581078e-205  506145
3    FIELD_6    624.473849   0.000000e+00  185188
32  FIELD_40    218.195791   0.000000e+00  477604
33  FIELD_41    190.887826  4.940656e-324  477522
20  FIELD_27    150.947600   2.908396e-66  510851
24  FIELD_31    105.924303   1.016687e-46  511285
34  FIELD_42     78.722052  1.134104e-130  477484
21  FIELD_28     56.641096   2.534035e-25  510652
29  FIELD_36     40.523601   0.000000e+00  111005
30  FIELD_37     37.348831   0.000000e+00  111162
2    FIELD_5     34.866681   5.532123e-49  164110
23  FIELD_30     32.242571   1.365220e-08   84337
27  FIELD_34     32.112864   0.000000e+00  104607
11  FIELD_18     30.274078   3.752842e-08  512852
28  FIELD_35     29.262341  5.851108e-314  104161
18  FIELD_25     22.798337   1.799714e-06  507382
14  FIELD_21     21.891899   2.885233e-06  507364
25  FIELD_32     21.874727   9.058847e-30  512013
22  FIELD_29     21.638015   4.009840e-10  511573
7   FIELD_14     10.788339   2.064345e-05  513022
1    FIELD_4      7.915001   1.240873e-09  503310
13  FIELD_20      6.432890   1.120291e-02  507347
19  FIELD_26      5.475630   1.928379e-02  507513

In [21]:
print(list(FvalPvalCorr[FvalPvalCorr.Count>50000].Cols)[:22])

['CLASS', 'FIELD_33', 'FIELD_15', 'FIELD_17', 'FIELD_7', 'FIELD_22', 'FIELD_38', 'FIELD_24', 'FIELD_6', 'FIELD_40', 'FIELD_41', 'FIELD_27', 'FIELD_31', 'FIELD_42', 'FIELD_28', 'FIELD_36', 'FIELD_37', 'FIELD_5', 'FIELD_30', 'FIELD_34', 'FIELD_18', 'FIELD_35']

In [22]:
# from sklearn.linear_model import LinearRegression
# from mlxtend.feature_selection import SequentialFeatureSelector as SFS
# from mlxtend.plotting import plot_sequential_feature_selection as plot_sfs
# from sklearn.ensemble import RandomForestRegressor

# lr = RandomForestRegressor()

# sfs = SFS(lr, 
#           k_features=13, 
#           forward=True, 
#           floating=False, 
#           scoring='neg_mean_squared_error',
#           cv=10)

# sfs = sfs.fit(x, y)
# fig = plot_sfs(sfs.get_metric_dict(), kind='std_err')

# plt.title('Sequential Forward Selection (w. StdErr)')
# plt.grid()
# plt.show()

NameError: name 'x' is not defined