In [13]:
import numpy as np
import pandas as pd 
import warnings

warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics as m

In [14]:
data= pd.read_csv('../sep19SexAndAgeAddedFINAL DATASET_ver2.txt',sep=',')
data=data.drop(columns=['B_DAY'])

In [15]:
data=data.query('FIELD_16 != 1 and FIELD_23 != 1')
data.head()

,Unnamed: 0,FIELD_1,FIELD_2,COMPARE,AGE,SEX,FIELD_3,FIELD_4,FIELD_5,FIELD_6,...,S004423,S004424,S005200,S007400,S008501,S008502,S008503,S008504,S010101,S010102
0,0,1000003,20130913,100000320130913,46.0,0.0,NaN,4,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0,14.0
1,1,1000003,20140613,100000320140613,47.0,0.0,NaN,4,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,16.0
2,2,1000003,20150917,100000320150917,48.0,0.0,1,4,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,16.0
3,3,1000003,20160617,100000320160617,49.0,0.0,NaN,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,18.0
4,4,1000003,20170608,100000320170608,50.0,0.0,NaN,4,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,18.0

In [ ]:
data2=data[['L103000', 'L103100', 'L101700', 'S001200',
       'L102900', 'S000300', 'L100700', 'L100800', 'S000200', 'L101300',
       'L190000', 'FIELD_33', 'S000501', 'S000502', 'L190400', 'L190800',
       'L190300', 'L100100', 'FIELD_38', 'L101000', 'L101600', 'FIELD_40',
       'L100300']]

In [16]:
x=data2[['L103100', 'L101700', 'S001200',
       'L102900', 'S000300', 'L100700', 'L100800', 'S000200', 'L101300',
       'L190000', 'FIELD_33', 'S000501', 'S000502', 'L190400', 'L190800',
       'L190300', 'L100100', 'FIELD_38', 'L101000', 'L101600', 'FIELD_40',
       'L100300']]

y=data2[['L103000']]

In [17]:
xtrain,xtest,ytrain,ytest=train_test_split(x, y, random_state=42, test_size=0.2)

In [18]:
regr = RandomForestRegressor(max_depth=7, random_state=0,verbose =0,n_estimators=500)
regr.fit(xtrain, ytrain) 
print(regr.feature_importances_)
ypred=regr.predict(xtest)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [ ]:

import math
print('mean_squared_error',mean_squared_error(ytest, ypred))
print('root mean_squared_error',math.sqrt(mean_squared_error(ytest, ypred)))
print('mean_absolute_error',mean_absolute_error(ytest, ypred))
print('r2_score',r2_score(ytest, ypred))

ypredPD=pd.DataFrame()
# ypredPD['t']=xtest['S000501_x'].values
ypredPD['t + 1']=ytest.values.ravel()
ypredPD['pred (t +1)']=ypred
ypredPD.head(30)

import matplotlib.patches as mpatches
plt.ylabel('Values')
plt.xlabel('index')
red_patch = mpatches.Patch(color='red', label='Actual data')
blue_patch = mpatches.Patch(color='blue', label='Predicted data')
plt.legend(handles=[red_patch,blue_patch])

ypredPD=ypredPD.sort_values(by=['t + 1'])
plt.scatter(np.arange(0,ypredPD.shape[0],1),ypredPD['pred (t +1)'][:ypredPD.shape[0]])
plt.plot(np.arange(0,ypredPD.shape[0],1),ypredPD['t + 1'][:ypredPD.shape[0]],color='red')
plt.show()

plt.ylabel('p*(t+1), Predicted data')
plt.xlabel('p(t+1), Actual data')
plt.scatter(ypredPD['t + 1'][:ypredPD.shape[0]],ypredPD['pred (t +1)'][:ypredPD.shape[0]])

ypredPD.tail(10)